"""remove unique constraint on is_current

Revision ID: dc59b686be3a
Revises: 86f35791102d
Create Date: 2026-03-02 12:06:54.699550

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "dc59b686be3a"
down_revision: Union[str, Sequence[str], None] = "86f35791102d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_billing_period_current"), table_name="billing_period")
    op.execute(
        "CREATE UNIQUE INDEX idx_billing_period_current_true ON billing_period (is_current) WHERE is_current = true;"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS idx_billing_period_current_true;")
    op.create_index(
        op.f("idx_billing_period_current"),
        "billing_period",
        ["is_current"],
        unique=True,
    )
    # ### end Alembic commands ###
