"""initial schema

Revision ID: 7828a51286bd
Revises:
Create Date: 2026-02-17 15:57:41.586885

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7828a51286bd"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "azure_service",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("service_category", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("idx_azure_service_name", "azure_service", ["name"], unique=False)

    op.create_table(
        "billing_period",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("start_date", "end_date", name="uq_billing_period_dates"),
    )
    op.create_index(
        "idx_billing_period_current", "billing_period", ["is_current"], unique=True
    )

    op.create_table(
        "daily_cost",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("billing_period_id", sa.Integer(), nullable=False),
        sa.Column("usage_date", sa.Date(), nullable=False),
        sa.Column("cost_amount", sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("LENGTH(currency_code) = 3", name="ck_currency_code_length"),
        sa.CheckConstraint("cost_amount >= 0", name="ck_daily_cost_amount_positive"),
        sa.ForeignKeyConstraint(
            ["billing_period_id"], ["billing_period.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "usage_date", "billing_period_id", name="uq_daily_cost_date_period"
        ),
    )
    op.create_index(
        "idx_daily_cost_billing_period",
        "daily_cost",
        ["billing_period_id"],
        unique=False,
    )
    op.create_index(
        "idx_daily_cost_usage_date",
        "daily_cost",
        ["usage_date"],
        unique=False,
        postgresql_using="btree",
    )

    op.create_table(
        "service_cost",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("billing_period_id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("cost_amount", sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("LENGTH(currency_code) = 3", name="ck_currency_code_length"),
        sa.CheckConstraint("cost_amount >= 0", name="ck_service_cost_amount_positive"),
        sa.ForeignKeyConstraint(
            ["billing_period_id"], ["billing_period.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["service_id"], ["azure_service.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "service_id", "billing_period_id", name="uq_service_cost_natural_key"
        ),
    )
    op.create_index(
        "idx_service_cost_fetched_at", "service_cost", ["fetched_at"], unique=False
    )
    op.create_index(
        "idx_service_cost_service_period",
        "service_cost",
        ["service_id", "billing_period_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_service_cost_service_period", table_name="service_cost")
    op.drop_index("idx_service_cost_fetched_at", table_name="service_cost")
    op.drop_table("service_cost")
    op.drop_index(
        "idx_daily_cost_usage_date", table_name="daily_cost", postgresql_using="btree"
    )
    op.drop_index("idx_daily_cost_billing_period", table_name="daily_cost")
    op.drop_table("daily_cost")
    op.drop_index("idx_billing_period_current", table_name="billing_period")
    op.drop_table("billing_period")
    op.drop_index("idx_azure_service_name", table_name="azure_service")
    op.drop_table("azure_service")
    # ### end Alembic commands ###
