"""add anomaly_log

Revision ID: ea4edfd99168
Revises: 5ee2a0553292
Create Date: 2026-03-03 18:09:23.013281

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ea4edfd99168"
down_revision: Union[str, Sequence[str], None] = "5ee2a0553292"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anomaly_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("service_name", sa.String(length=255), nullable=False),
        sa.Column(
            "period_type",
            sa.Enum("DAILY", "MONTHLY", name="periodtype", create_type=False),
            nullable=False,
        ),
        sa.Column("reference_date", sa.Date(), nullable=False),
        sa.Column("current_cost", sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column(
            "absolute_component", sa.DECIMAL(precision=15, scale=2), nullable=True
        ),
        sa.Column(
            "statistical_component", sa.DECIMAL(precision=15, scale=2), nullable=True
        ),
        sa.Column(
            "percentage_component", sa.DECIMAL(precision=15, scale=2), nullable=True
        ),
        sa.Column(
            "computed_threshold", sa.DECIMAL(precision=15, scale=2), nullable=False
        ),
        sa.Column("winning_component", sa.String(length=20), nullable=False),
        sa.Column("is_alert_fired", sa.Boolean(), nullable=False),
        sa.Column("alert_event_id", sa.Integer(), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_event_id"], ["alert_event.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["service_id"], ["azure_service.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_anomaly_log_detected_at", "anomaly_log", ["detected_at"], unique=False
    )
    op.create_index(
        "idx_anomaly_log_is_alert_fired",
        "anomaly_log",
        ["is_alert_fired"],
        unique=False,
    )
    op.create_index(
        "idx_anomaly_log_service_period",
        "anomaly_log",
        ["service_id", "period_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_anomaly_log_service_period", table_name="anomaly_log")
    op.drop_index("idx_anomaly_log_is_alert_fired", table_name="anomaly_log")
    op.drop_index("idx_anomaly_log_detected_at", table_name="anomaly_log")
    op.drop_table("anomaly_log")
    # ### end Alembic commands ###
