"""add service_id to daily_cost

Revision ID: 86f35791102d
Revises: 7828a51286bd
Create Date: 2026-02-23 23:55:27.141090

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86f35791102d"
down_revision: Union[str, Sequence[str], None] = "7828a51286bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("daily_cost", sa.Column("service_id", sa.Integer(), nullable=False))
    op.drop_constraint(op.f("uq_daily_cost_date_period"), "daily_cost", type_="unique")
    op.create_index(
        "idx_daily_cost_service_date",
        "daily_cost",
        ["service_id", "usage_date"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_daily_cost_date_service_period",
        "daily_cost",
        ["usage_date", "service_id", "billing_period_id"],
    )
    op.create_foreign_key(
        None, "daily_cost", "azure_service", ["service_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "daily_cost", type_="foreignkey")
    op.drop_constraint(
        "uq_daily_cost_date_service_period", "daily_cost", type_="unique"
    )
    op.drop_index("idx_daily_cost_service_date", table_name="daily_cost")
    op.create_unique_constraint(
        op.f("uq_daily_cost_date_period"),
        "daily_cost",
        ["usage_date", "billing_period_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("daily_cost", "service_id")
    # ### end Alembic commands ###
