"""add alert & anomaly tables

Revision ID: 5ee2a0553292
Revises: dc59b686be3a
Create Date: 2026-03-03 15:47:38.391782

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5ee2a0553292"
down_revision: Union[str, Sequence[str], None] = "dc59b686be3a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anomaly_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("k_value", sa.Float(), nullable=False),
        sa.Column("percentage_buffer", sa.Float(), nullable=False),
        sa.Column("alert_history_days", sa.Integer(), nullable=False),
        sa.Column("alert_history_months", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "alert_threshold",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column(
            "period_type",
            sa.Enum("DAILY", "MONTHLY", name="periodtype", create_type=True),
            nullable=False,
        ),
        sa.Column(
            "absolute_threshold", sa.DECIMAL(precision=15, scale=2), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"], ["azure_service.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "service_id", "period_type", name="uq_alert_threshold_service_period"
        ),
    )
    op.create_table(
        "alert_event",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("threshold_id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column(
            "period_type",
            sa.Enum("DAILY", "MONTHLY", name="periodtype", create_type=False),
            nullable=False,
        ),
        sa.Column("reference_date", sa.Date(), nullable=False),
        sa.Column("current_cost", sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column(
            "computed_threshold", sa.DECIMAL(precision=15, scale=2), nullable=False
        ),
        sa.Column(
            "absolute_component", sa.DECIMAL(precision=15, scale=2), nullable=True
        ),
        sa.Column(
            "statistical_component", sa.DECIMAL(precision=15, scale=2), nullable=True
        ),
        sa.Column(
            "percentage_component", sa.DECIMAL(precision=15, scale=2), nullable=True
        ),
        sa.Column("winning_component", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"], ["azure_service.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["threshold_id"], ["alert_threshold.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_alert_event_service_period_status",
        "alert_event",
        ["service_id", "period_type", "status"],
        unique=False,
    )
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_billing_period_current_true "
        "ON billing_period (is_current) WHERE is_current = true;"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_alert_event_service_period_status", table_name="alert_event")
    op.drop_table("alert_event")
    op.drop_table("alert_threshold")
    op.drop_table("anomaly_settings")
    # ### end Alembic commands ###
